In [1]:
import pandas as pd

In [2]:
#PART ONE
#loading all datas
cell = pd.read_csv('cell_phones.csv')
population = pd.read_csv('population1.csv')
geo = pd.read_csv('ddf--entities--geo--country.csv')

In [3]:
#PART TWO
merged_data = pd.merge(cell,population,on=['Country','year'])

In [4]:
geo.rename(columns = {'country':'geo','name':'Country'}, inplace=True)

In [5]:
geo.head()

,geo,g77_and_oecd_countries,income_3groups,income_groups,is--country,iso3166_1_alpha2,iso3166_1_alpha3,iso3166_1_numeric,iso3166_2,landlocked,...,longitude,main_religion_2008,Country,un_sdg_ldc,un_sdg_region,un_state,unicef_region,unicode_region_subtag,world_4region,world_6region
0,abkh,others,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Abkhazia,NaN,NaN,False,NaN,NaN,europe,europe_central_asia
1,abw,others,high_income,high_income,True,AW,ABW,533.0,NaN,coastline,...,-69.96667,christian,Aruba,un_not_least_developed,un_latin_america_and_the_caribbean,False,NaN,AW,americas,america
2,afg,g77,low_income,low_income,True,AF,AFG,4.0,NaN,landlocked,...,66.00000,muslim,Afghanistan,un_least_developed,un_central_and_southern_asia,True,sa,AF,asia,south_asia
3,ago,g77,middle_income,lower_middle_income,True,AO,AGO,24.0,NaN,coastline,...,18.50000,christian,Angola,un_least_developed,un_sub_saharan_africa,True,ssa,AO,africa,sub_saharan_africa
4,aia,others,NaN,NaN,True,AI,AIA,660.0,NaN,coastline,...,-63.05000,christian,Anguilla,un_not_least_developed,un_latin_america_and_the_caribbean,False,NaN,AI,americas,america

In [6]:
data = {
    'geo':geo['geo'],
    'Country' : geo['Country']
}


data_df = pd.DataFrame(data)

In [7]:
merged_data = pd.merge(merged_data,data_df)

In [8]:
merged_data

           Country  year  cell_phones_total  population  geo
0      Afghanistan  1960                0.0     9000000  afg
1      Afghanistan  1961                0.0     9170000  afg
2      Afghanistan  1962                0.0     9350000  afg
3      Afghanistan  1963                0.0     9540000  afg
4      Afghanistan  1964                0.0     9740000  afg
5      Afghanistan  1965                0.0     9960000  afg
6      Afghanistan  1966                0.0    10200000  afg
7      Afghanistan  1967                0.0    10400000  afg
8      Afghanistan  1968                0.0    10600000  afg
9      Afghanistan  1969                0.0    10900000  afg
10     Afghanistan  1970                0.0    11200000  afg
11     Afghanistan  1971                0.0    11500000  afg
12     Afghanistan  1972                0.0    11800000  afg
13     Afghanistan  1973                0.0    12100000  afg
14     Afghanistan  1974                0.0    12400000  afg
15     Afghanistan  1975                0.0    12700000  afg
16     Afghanistan  1976                0.0    12900000  afg
17     Afghanistan  1977                0.0    13200000  afg
18     Afghanistan  1978                0.0    13300000  afg
19     Afghanistan  1979                0.0    13400000  afg
20     Afghanistan  1980                0.0    13400000  afg
21     Afghanistan  1981                0.0    13200000  afg
22     Afghanistan  1982                0.0    12900000  afg
23     Afghanistan  1983                0.0    12500000  afg
24     Afghanistan  1984                0.0    12200000  afg
25     Afghanistan  1985                0.0    11900000  afg
26     Afghanistan  1986                0.0    11700000  afg
27     Afghanistan  1987                0.0    11600000  afg
28     Afghanistan  1988                0.0    11600000  afg
29     Afghanistan  1989                0.0    11900000  afg
...            ...   ...                ...         ...  ...
11610     Zimbabwe  1990                0.0    10400000  zwe
11611     Zimbabwe  1991                0.0    10700000  zwe
11612     Zimbabwe  1992                0.0    10900000  zwe
11613     Zimbabwe  1993                0.0    11100000  zwe
11614     Zimbabwe  1994                0.0    11300000  zwe
11615     Zimbabwe  1995                0.0    11400000  zwe
11616     Zimbabwe  1996                0.0    11500000  zwe
11617     Zimbabwe  1997             5730.0    11700000  zwe
11618     Zimbabwe  1998            19000.0    11700000  zwe
11619     Zimbabwe  1999           174000.0    11800000  zwe
11620     Zimbabwe  2000           266000.0    11900000  zwe
11621     Zimbabwe  2001           314000.0    11900000  zwe
11622     Zimbabwe  2002           339000.0    12000000  zwe
11623     Zimbabwe  2003           364000.0    12000000  zwe
11624     Zimbabwe  2004           426000.0    12000000  zwe
11625     Zimbabwe  2005           647000.0    12100000  zwe
11626     Zimbabwe  2006           849000.0    12200000  zwe
11627     Zimbabwe  2007          1230000.0    12300000  zwe
11628     Zimbabwe  2008          1650000.0    12400000  zwe
11629     Zimbabwe  2009          3990000.0    12500000  zwe
11630     Zimbabwe  2010          7700000.0    12700000  zwe
11631     Zimbabwe  2011          9200000.0    12900000  zwe
11632     Zimbabwe  2012         12600000.0    13100000  zwe
11633     Zimbabwe  2013         13600000.0    13400000  zwe
11634     Zimbabwe  2014         11800000.0    13600000  zwe
11635     Zimbabwe  2015         12800000.0    13800000  zwe
11636     Zimbabwe  2016         12900000.0    14000000  zwe
11637     Zimbabwe  2017         14100000.0    14200000  zwe
11638     Zimbabwe  2018         12900000.0    14400000  zwe
11639     Zimbabwe  2019         13200000.0    14600000  zwe

[11640 rows x 5 columns]

In [9]:
#PART THREE
merged_data['cell_phone per person'] = merged_data['cell_phones_total']/merged_data['population']

In [10]:
merged_data

,Country,year,cell_phones_total,population,geo,cell_phone per person
0,Afghanistan,1960,0.0,9000000,afg,0.000000
1,Afghanistan,1961,0.0,9170000,afg,0.000000
2,Afghanistan,1962,0.0,9350000,afg,0.000000
3,Afghanistan,1963,0.0,9540000,afg,0.000000
4,Afghanistan,1964,0.0,9740000,afg,0.000000
5,Afghanistan,1965,0.0,9960000,afg,0.000000
6,Afghanistan,1966,0.0,10200000,afg,0.000000
7,Afghanistan,1967,0.0,10400000,afg,0.000000
8,Afghanistan,1968,0.0,10600000,afg,0.000000
9,Afghanistan,1969,0.0,10900000,afg,0.000000
10,Afghanistan,1970,0.0,11200000,afg,0.000000
11,Afghanistan,1971,0.0,11500000,afg,0.000000
12,Afghanistan,1972,0.0,11800000,afg,0.000000
13,Afghanistan,1973,0.0,12100000,afg,0.000000
14,Afghanistan,1974,0.0,12400000,afg,0.000000
15,Afghanistan,1975,0.0,12700000,afg,0.000000
16,Afghanistan,1976,0.0,12900000,afg,0.000000
17,Afghanistan,1977,0.0,13200000,afg,0.000000
18,Afghanistan,1978,0.0,13300000,afg,0.000000
19,Afghanistan,1979,0.0,13400000,afg,0.000000
20,Afghanistan,1980,0.0,13400000,afg,0.000000
21,Afghanistan,1981,0.0,13200000,afg,0.000000
22,Afghanistan,1982,0.0,12900000,afg,0.000000
23,Afghanistan,1983,0.0,12500000,afg,0.000000
24,Afghanistan,1984,0.0,12200000,afg,0.000000
25,Afghanistan,1985,0.0,11900000,afg,0.000000
26,Afghanistan,1986,0.0,11700000,afg,0.000000
27,Afghanistan,1987,0.0,11600000,afg,0.000000
28,Afghanistan,1988,0.0,11600000,afg,0.000000
29,Afghanistan,1989,0.0,11900000,afg,0.000000
...,...,...,...,...,...,...
11610,Zimbabwe,1990,0.0,10400000,zwe,0.000000
11611,Zimbabwe,1991,0.0,10700000,zwe,0.000000
11612,Zimbabwe,1992,0.0,10900000,zwe,0.000000
11613,Zimbabwe,1993,0.0,11100000,zwe,0.000000
11614,Zimbabwe,1994,0.0,11300000,zwe,0.000000
11615,Zimbabwe,1995,0.0,11400000,zwe,0.000000
11616,Zimbabwe,1996,0.0,11500000,zwe,0.000000
11617,Zimbabwe,1997,5730.0,11700000,zwe,0.000490
11618,Zimbabwe,1998,19000.0,11700000,zwe,0.001624
11619,Zimbabwe,1999,174000.0,11800000,zwe,0.014746
11620,Zimbabwe,2000,266000.0,11900000,zwe,0.022353
11621,Zimbabwe,2001,314000.0,11900000,zwe,0.026387
11622,Zimbabwe,2002,339000.0,12000000,zwe,0.028250
11623,Zimbabwe,2003,364000.0,12000000,zwe,0.030333
11624,Zimbabwe,2004,426000.0,12000000,zwe,0.035500
11625,Zimbabwe,2005,647000.0,12100000,zwe,0.053471
11626,Zimbabwe,2006,849000.0,12200000,zwe,0.069590
11627,Zimbabwe,2007,1230000.0,12300000,zwe,0.100000
11628,Zimbabwe,2008,1650000.0,12400000,zwe,0.133065
11629,Zimbabwe,2009,3990000.0,12500000,zwe,0.319200
11630,Zimbabwe,2010,7700000.0,12700000,zwe,0.606299
11631,Zimbabwe,2011,9200000.0,12900000,zwe,0.713178
11632,Zimbabwe,2012,12600000.0,13100000,zwe,0.961832
11633,Zimbabwe,2013,13600000.0,13400000,zwe,1.014925
11634,Zimbabwe,2014,11800000.0,13600000,zwe,0.867647
11635,Zimbabwe,2015,12800000.0,13800000,zwe,0.927536
11636,Zimbabwe,2016,12900000.0,14000000,zwe,0.921429
11637,Zimbabwe,2017,14100000.0,14200000,zwe,0.992958
11638,Zimbabwe,2018,12900000.0,14400000,zwe,0.895833
11639,Zimbabwe,2019,13200000.0,14600000,zwe,0.904110

In [11]:
merged_data['geo'] = merged_data['geo'].str.upper()

In [12]:
merged_data

,Country,year,cell_phones_total,population,geo,cell_phone per person
0,Afghanistan,1960,0.0,9000000,AFG,0.000000
1,Afghanistan,1961,0.0,9170000,AFG,0.000000
2,Afghanistan,1962,0.0,9350000,AFG,0.000000
3,Afghanistan,1963,0.0,9540000,AFG,0.000000
4,Afghanistan,1964,0.0,9740000,AFG,0.000000
5,Afghanistan,1965,0.0,9960000,AFG,0.000000
6,Afghanistan,1966,0.0,10200000,AFG,0.000000
7,Afghanistan,1967,0.0,10400000,AFG,0.000000
8,Afghanistan,1968,0.0,10600000,AFG,0.000000
9,Afghanistan,1969,0.0,10900000,AFG,0.000000
10,Afghanistan,1970,0.0,11200000,AFG,0.000000
11,Afghanistan,1971,0.0,11500000,AFG,0.000000
12,Afghanistan,1972,0.0,11800000,AFG,0.000000
13,Afghanistan,1973,0.0,12100000,AFG,0.000000
14,Afghanistan,1974,0.0,12400000,AFG,0.000000
15,Afghanistan,1975,0.0,12700000,AFG,0.000000
16,Afghanistan,1976,0.0,12900000,AFG,0.000000
17,Afghanistan,1977,0.0,13200000,AFG,0.000000
18,Afghanistan,1978,0.0,13300000,AFG,0.000000
19,Afghanistan,1979,0.0,13400000,AFG,0.000000
20,Afghanistan,1980,0.0,13400000,AFG,0.000000
21,Afghanistan,1981,0.0,13200000,AFG,0.000000
22,Afghanistan,1982,0.0,12900000,AFG,0.000000
23,Afghanistan,1983,0.0,12500000,AFG,0.000000
24,Afghanistan,1984,0.0,12200000,AFG,0.000000
25,Afghanistan,1985,0.0,11900000,AFG,0.000000
26,Afghanistan,1986,0.0,11700000,AFG,0.000000
27,Afghanistan,1987,0.0,11600000,AFG,0.000000
28,Afghanistan,1988,0.0,11600000,AFG,0.000000
29,Afghanistan,1989,0.0,11900000,AFG,0.000000
...,...,...,...,...,...,...
11610,Zimbabwe,1990,0.0,10400000,ZWE,0.000000
11611,Zimbabwe,1991,0.0,10700000,ZWE,0.000000
11612,Zimbabwe,1992,0.0,10900000,ZWE,0.000000
11613,Zimbabwe,1993,0.0,11100000,ZWE,0.000000
11614,Zimbabwe,1994,0.0,11300000,ZWE,0.000000
11615,Zimbabwe,1995,0.0,11400000,ZWE,0.000000
11616,Zimbabwe,1996,0.0,11500000,ZWE,0.000000
11617,Zimbabwe,1997,5730.0,11700000,ZWE,0.000490
11618,Zimbabwe,1998,19000.0,11700000,ZWE,0.001624
11619,Zimbabwe,1999,174000.0,11800000,ZWE,0.014746
11620,Zimbabwe,2000,266000.0,11900000,ZWE,0.022353
11621,Zimbabwe,2001,314000.0,11900000,ZWE,0.026387
11622,Zimbabwe,2002,339000.0,12000000,ZWE,0.028250
11623,Zimbabwe,2003,364000.0,12000000,ZWE,0.030333
11624,Zimbabwe,2004,426000.0,12000000,ZWE,0.035500
11625,Zimbabwe,2005,647000.0,12100000,ZWE,0.053471
11626,Zimbabwe,2006,849000.0,12200000,ZWE,0.069590
11627,Zimbabwe,2007,1230000.0,12300000,ZWE,0.100000
11628,Zimbabwe,2008,1650000.0,12400000,ZWE,0.133065
11629,Zimbabwe,2009,3990000.0,12500000,ZWE,0.319200
11630,Zimbabwe,2010,7700000.0,12700000,ZWE,0.606299
11631,Zimbabwe,2011,9200000.0,12900000,ZWE,0.713178
11632,Zimbabwe,2012,12600000.0,13100000,ZWE,0.961832
11633,Zimbabwe,2013,13600000.0,13400000,ZWE,1.014925
11634,Zimbabwe,2014,11800000.0,13600000,ZWE,0.867647
11635,Zimbabwe,2015,12800000.0,13800000,ZWE,0.927536
11636,Zimbabwe,2016,12900000.0,14000000,ZWE,0.921429
11637,Zimbabwe,2017,14100000.0,14200000,ZWE,0.992958
11638,Zimbabwe,2018,12900000.0,14400000,ZWE,0.895833
11639,Zimbabwe,2019,13200000.0,14600000,ZWE,0.904110

In [13]:
#PART FOUR
merged_data.describe()

               year  cell_phones_total    population  cell_phone per person
count  11640.000000       1.164000e+04  1.164000e+04           11640.000000
mean    1989.500000       7.875722e+06  2.710307e+07               0.235536
std       17.318846       5.572496e+07  1.086187e+08               0.433303
min     1960.000000       0.000000e+00  4.380000e+03               0.000000
25%     1974.750000       0.000000e+00  1.117500e+06               0.000000
50%     1989.500000       0.000000e+00  5.100000e+06               0.000000
75%     2004.250000       5.615000e+05  1.590000e+07               0.233667
max     2019.000000       1.730000e+09  1.430000e+09               2.126068

In [16]:
merged_data[merged_data['year'] == 2017]

,Country,year,cell_phones_total,population,geo,cell_phone per person
57,Afghanistan,2017,23900000.0,36300000,AFG,0.658402
117,Albania,2017,3630000.0,2880000,ALB,1.260417
177,Algeria,2017,45800000.0,41400000,DZA,1.106280
237,Andorra,2017,80300.0,77000,AND,1.042857
297,Angola,2017,13300000.0,29800000,AGO,0.446309
357,Antigua and Barbuda,2017,184000.0,95400,ATG,1.928721
417,Argentina,2017,61900000.0,43900000,ARG,1.410023
477,Armenia,2017,3490000.0,2940000,ARM,1.187075
537,Australia,2017,26700000.0,24600000,AUS,1.085366
597,Austria,2017,10900000.0,8820000,AUT,1.235828
657,Azerbaijan,2017,10100000.0,9850000,AZE,1.025381
717,Bahamas,2017,354000.0,382000,BHS,0.926702
777,Bahrain,2017,2360000.0,1490000,BHR,1.583893
837,Bangladesh,2017,151000000.0,160000000,BGD,0.943750
897,Barbados,2017,330000.0,286000,BRB,1.153846
957,Belarus,2017,11400000.0,9450000,BLR,1.206349
1017,Belgium,2017,11400000.0,11400000,BEL,1.000000
1077,Belize,2017,239000.0,376000,BLZ,0.635638
1137,Benin,2017,8770000.0,11200000,BEN,0.783036
1197,Bhutan,2017,731000.0,746000,BTN,0.979893
1257,Bolivia,2017,11000000.0,11200000,BOL,0.982143
1317,Bosnia and Herzegovina,2017,3440000.0,3350000,BIH,1.026866
1377,Botswana,2017,3240000.0,2210000,BWA,1.466063
1437,Brazil,2017,218000000.0,208000000,BRA,1.048077
1497,Brunei,2017,545000.0,424000,BRN,1.285377
1557,Bulgaria,2017,8530000.0,7100000,BGR,1.201408
1617,Burkina Faso,2017,17900000.0,19200000,BFA,0.932292
1677,Burundi,2017,5920000.0,10800000,BDI,0.548148
1737,Cambodia,2017,18600000.0,16000000,KHM,1.162500
1797,Cameroon,2017,20100000.0,24600000,CMR,0.817073
...,...,...,...,...,...,...
9897,St. Vincent and the Grenadines,2017,116000.0,110000,VCT,1.054545
9957,Sudan,2017,28600000.0,40800000,SDN,0.700980
10017,Suriname,2017,796000.0,571000,SUR,1.394046
10077,Sweden,2017,12500000.0,9900000,SWE,1.262626
10137,Switzerland,2017,11100000.0,8460000,CHE,1.312057
10197,Syria,2017,15400000.0,17100000,SYR,0.900585
10257,Tajikistan,2017,9900000.0,8880000,TJK,1.114865
10317,Tanzania,2017,40000000.0,54700000,TZA,0.731261
10377,Thailand,2017,122000000.0,69200000,THA,1.763006
10437,Timor-Leste,2017,1560000.0,1240000,TLS,1.258065
10497,Togo,2017,6070000.0,7700000,TGO,0.788312
10557,Tonga,2017,108000.0,102000,TON,1.058824
10617,Trinidad and Tobago,2017,2030000.0,1380000,TTO,1.471014
10677,Tunisia,2017,14300000.0,11400000,TUN,1.254386
10737,Turkey,2017,77800000.0,81100000,TUR,0.959309
10797,Turkmenistan,2017,9380000.0,5760000,TKM,1.628472
10857,Tuvalu,2017,8000.0,11400,TUV,0.701754
10917,Uganda,2017,24900000.0,41200000,UGA,0.604369
10977,Ukraine,2017,55700000.0,44500000,UKR,1.251685
11037,United Arab Emirates,2017,19800000.0,9490000,ARE,2.086407
11097,United Kingdom,2017,79100000.0,66700000,GBR,1.185907
11157,United States,2017,400000000.0,325000000,USA,1.230769
11217,Uruguay,2017,5100000.0,3440000,URY,1.482558
11277,Uzbekistan,2017,24300000.0,32000000,UZB,0.759375
11337,Vanuatu,2017,228000.0,285000,VUT,0.800000
11397,Venezuela,2017,24500000.0,29400000,VEN,0.833333
11457,Vietnam,2017,120000000.0,94600000,VNM,1.268499
11517,Yemen,2017,15400000.0,27800000,YEM,0.553957
11577,Zambia,2017,13400000.0,16900000,ZMB,0.792899
11637,Zimbabwe,2017,14100000.0,14200000,ZWE,0.992958

In [20]:
merged_data[merged_data['year'] == 2017].sort_values(by='cell_phones_total',ascending=False).head(5)

,Country,year,cell_phones_total,population,geo,cell_phone per person
2157,China,2017,1.470000e+09,1420000000,CHN,1.035211
4617,India,2017,1.170000e+09,1340000000,IND,0.873134
4677,Indonesia,2017,4.350000e+08,265000000,IDN,1.641509
11157,United States,2017,4.000000e+08,325000000,USA,1.230769
8577,Russia,2017,2.270000e+08,146000000,RUS,1.554795